name: Publish to the Chrome Web Store

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment'
        required: true
        default: 'develop'
        type: choice
        options:
          - develop
          - staging
          - beta

jobs:
  set-build-params:
    uses: ./.github/workflows/set-build-params.yaml

#  build:
#    needs: set-build-params
#    uses: virtru-corp/.github/.github/workflows/gmail-build.yaml@v1
#    with:
#      environment: '${{ needs.set-build-params.outputs.environment }}'
#      channel: '${{ needs.set-build-params.outputs.channel }}'
#      extension-id: '${{ needs.set-build-params.outputs.extension_id }}'
#      is-release-build: "${{ needs.set-build-params.outputs.is_release_build == 'true' }}"

  publish:
    needs: [set-build-params]
    uses: ./.github/workflows/publish.yaml
    with:
      artifact: 'chrome'
      extension_id: '${{ needs.set-build-params.outputs.extension_id }}'
      channel: '${{ inputs.environment }}'