name: Publish to the Chrome Web Store

on:
  workflow_dispatch:

jobs:
  check-branch:
    if: "${{ github.ref_name == 'develop' || github.ref_name == 'staging' ||  github.ref_name == 'beta' }}"
    runs-on: ubuntu-latest

  set-build-params:
    needs: [check-branch]
    uses: ./.github/workflows/set-build-params.yaml

  log:
    needs: [check-branch]
    runs-on: ubuntu-latest
    steps:
      - name: Log the inputs
        run: |
          echo ${{ github.ref_name }} 

  publish:
    needs: [set-build-params]
    uses: ./.github/workflows/publish.yaml
    with:
      artifact: 'chrome'
      extension_id: '${{ needs.set-build-params.outputs.extension_id }}'
      channel: '${{ github.ref_name }} '