name: Publish to the Chrome Web Store

on:
  workflow_dispatch:

jobs:
  branch-warn:
    # if: "${{ github.ref_name != 'develop' || github.ref_name != 'staging' ||  github.ref_name != 'beta' }}"
    # if: ${{ !contains(fromJSON('["develop","staging","beta"]'), github.ref_name) }}
    runs-on: ubuntu-latest

    steps:
      - name: Warning message
        if: ${{ !contains(fromJSON('["develop","staging","beta"]'), github.ref_name) }}
        run: echo 'Publishing is allowed only for "develop", "staging" and "beta"' >> $GITHUB_STEP_SUMMARY

  set-build-params:
    # if: "${{ github.ref_name == 'develop' || github.ref_name == 'staging' ||  github.ref_name == 'beta' }}"
    if: ${{ contains(fromJSON('["develop","staging","beta"]'), github.ref_name) }}
    needs: [branch-warn]
    uses: ./.github/workflows/set-build-params.yaml

  log:
    needs: [set-build-params]
    runs-on: ubuntu-latest
    steps:
      - name: Log the inputs
        run: |
          echo ${{ github.ref_name }} 

  publish:
    needs: [log, set-build-params]
    uses: ./.github/workflows/publish.yaml
    with:
      artifact: 'chrome'
      extension_id: '${{ needs.set-build-params.outputs.extension_id }}'
      channel: '${{ github.ref_name }} '
