name: Publish to the Chrome Web Store

on:
  workflow_dispatch:

jobs:
  check-branch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Exit if the branch is not master
        run: |
          if [[ "${{ github.ref_name }}" != "develop" && "${{ github.ref_name }}" != "staging" && "${{ github.ref_name }}" != "beta" ]]; then
            echo "Branch is not develop, staging, or beta, exiting."
            exit 0
          fi

  set-build-params:
    uses: ./.github/workflows/set-build-params.yaml

  log:
    runs-on: ubuntu-latest
    steps:
      - name: Log the inputs
        run: |
          echo ${{ github.ref_name }} 

  publish:
    needs: [set-build-params]
    uses: ./.github/workflows/publish.yaml
    with:
      artifact: 'chrome'
      extension_id: '${{ needs.set-build-params.outputs.extension_id }}'
      channel: '${{ github.ref_name }} '